name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          working-directory: /home/runner/work/CyAuto_Testing/CyAuto_Testing/cySupport/cypress/e2e/1-getting-started
          project: ./1-getting-started/
          #spec: cypress/e2e/1-getting-started/iframeHandle.cy.js
          browser: chrome
          headed: false
