name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          #working-directory: cypress/e2e/
          #project: cypress/e2e/
          #spec: cypress/e2e/1-getting-started/iframeHandle.cy.js
          spec: |
            cypress/e2e/1-getting-started/iframeHandle.cy.js
            cypress/**/**/*.cy.js
          browser: chrome
          headed: false
