name: Cypress tests
on: push
jobs:
  cypress-run:
    name: Cypress run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          #spec: cypress/e2e/1-getting-started/iframeHandle.cy.js   #specific file
          spec: cypress/**/**/*.cy.js   #all files from e2e/1-getting-started folder
          browser: chrome
          headed: true
